### ISSUE TITLE
Update to scalajs 1.1.1

### ISSUE THREAD

**Issue by elyphas** [OutWatch/outwatch-libs#3]
I am updating the library to scalajs 1.1.1
because I need it for my app.

this is one of my first tries on github.

Sorry if I am doing wrong, I will try to make it better if something  bad happens.

I am not sure if the pull request was made by the way. :P 

but in my local the lib is working with `scalajs 1.1.1`

**Comment by elyphas** [comment]
I have updated based on the comments but I don't know if the `commits` have arrives on the master.

**Comment by cornerman** [comment]
Thank you again!
